services:
  mymongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - prateek-mongo:/data/db
  my_custom_app:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/app

volumes:
  prateek-mongo:
