services:
  mongoDB:
    image: mongo
    container_name: prateekMongo
    ports:
      - "27017:27017"
    volumes:
      - prateekVolume2:/data/db
  prateek_app:
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    
volumes:
  prateekVolume2: